// pdcdispa.h
// Dispatch indices for PD-Chess ObjectWindows interface
// (C) Copyright 1994 by Tom Weatherhead

#define CM_FILEEXIT		201
#define CM_GAMEOPTIONS		202
#define CM_GAMEPLAY		203
#define CM_ABOUT		204

#define ID_WHUMANBTN		101
#define ID_WCOMPBTN		102
#define ID_WPLAYERBOX		103
#define ID_WLEVELEDIT		104
#define ID_BHUMANBTN		105
#define ID_BCOMPBTN		106
#define ID_BPLAYERBOX		107
#define ID_BLEVELEDIT		108

// ******** End of pdcdispa.h ********
